"""TranslationFieldAndReferenceValidator: three codes plus two missing_required_field passes.

The expectations come from six probe feeds, each named in the test that uses it:

- `trfeed` covers every branch of a healthy feed: one- and two-key parents, an unknown table,
  a table the feed lacks, and field_value colliding with each id;
- `trnokey` covers a parent with no key columns at all (feed_info.txt);
- `trmixed` covers an unrelated table failing to load;
- `trfail2` covers the referenced table failing to load;
- `trkeys` covers the six key-resolution shapes of the generated byTranslationKey;
- `tr_baddate` and the `u_*` feeds cover the conversions, including the ones that abort the
  validator rather than missing the lookup.
"""

from __future__ import annotations

import datetime

import pytest

from fakefeed import FakeFeed
from gtfs_validator.context import Context
from gtfs_validator.rules import registry

CTX = Context(date=datetime.date(2026, 7, 25), country_code="US")


def translation(
    number, table, field="stop_name", language="fr", record_id=None, sub_id=None, field_value=None
):
    return {
        "_row_number": number,
        "table_name": table,
        "field_name": field,
        "language": language,
        "translation": "Valeur",
        "record_id": record_id,
        "record_sub_id": sub_id,
        "field_value": field_value,
    }


STOPS = [
    {"_row_number": 2, "stop_id": "S1", "stop_name": "Stop One"},
    {"_row_number": 3, "stop_id": "S2", "stop_name": "Stop Two"},
]
STOP_TIMES = [
    {"_row_number": 2, "trip_id": "T1", "stop_id": "S1", "stop_sequence": 1},
    {"_row_number": 3, "trip_id": "T1", "stop_id": "S2", "stop_sequence": 2},
]
# The trfeed rows, in file order.
TRANSLATIONS = [
    translation(2, "stops", record_id="S1"),
    translation(3, "stops", record_id="NOPE"),
    translation(4, "stops"),
    translation(5, "stops", record_id="S1", sub_id="EXTRA"),
    translation(6, "stop_times", field="stop_headsign", record_id="T1", sub_id="1"),
    translation(7, "stop_times", field="stop_headsign", record_id="T1", sub_id="99"),
    translation(8, "stop_times", field="stop_headsign", record_id="T1"),
    translation(9, "nosuchtable", field="some_field", record_id="X"),
    translation(10, "frequencies", field="headway_secs", record_id="T1"),
    translation(11, "stops", field_value="Old Name"),
    translation(12, "stops", record_id="S1", field_value="Old Name"),
    translation(13, "stops", record_id="S1", sub_id="SUB", field_value="Old Name"),
]
TABLES = {"stops.txt": STOPS, "stop_times.txt": STOP_TIMES, "translations.txt": TRANSLATIONS}

MEASURED = {
    "translation_unknown_table_name": [
        {"csvRowNumber": 9, "tableName": "nosuchtable"},
        {"csvRowNumber": 10, "tableName": "frequencies"},
    ],
    "translation_unexpected_value": [
        {"csvRowNumber": 5, "fieldName": "record_sub_id", "fieldValue": "EXTRA"},
        {"csvRowNumber": 12, "fieldName": "record_id", "fieldValue": "S1"},
        {"csvRowNumber": 13, "fieldName": "record_id", "fieldValue": "S1"},
        {"csvRowNumber": 13, "fieldName": "record_sub_id", "fieldValue": "SUB"},
    ],
    "translation_foreign_key_violation": [
        {"csvRowNumber": 3, "tableName": "stops", "recordId": "NOPE", "recordSubId": ""},
        {"csvRowNumber": 7, "tableName": "stop_times", "recordId": "T1", "recordSubId": "99"},
    ],
}


def fire(code, tables=None, unindexable=frozenset()):
    registry.load_rules()
    feed = FakeFeed(TABLES if tables is None else tables, unindexable=unindexable)
    return [n.context for n in registry.FILE_REGISTRY[code].func(feed, CTX)]


def sorted_rows(rows):
    return sorted(rows, key=lambda row: sorted(row.items()))


@pytest.mark.parametrize(("code", "expected"), sorted(MEASURED.items()))
def test_translation_rule_matches_the_jar(code, expected):
    assert sorted_rows(fire(code)) == sorted_rows(expected)


def test_the_reference_passes_report_the_ids_the_parent_calls_for():
    """`trfeed` rows 4 and 8: stops.txt has one key column so a missing record_id is reported,
    and stop_times.txt has two so a missing record_sub_id is as well."""
    got = [row for row in fire("missing_required_field") if row["filename"] == "translations.txt"]
    assert sorted_rows(got) == sorted_rows(
        [
            {"filename": "translations.txt", "csvRowNumber": 4, "fieldName": "record_id"},
            {"filename": "translations.txt", "csvRowNumber": 8, "fieldName": "record_sub_id"},
        ]
    )


def test_a_record_sub_id_matches_a_numeric_key_column():
    """`trfeed` row 6 names stop_sequence 1 as the string "1" and the jar accepts it, so the
    comparison is on the rendered value rather than the stored type."""
    violations = [row["csvRowNumber"] for row in fire("translation_foreign_key_violation")]
    assert 6 not in violations
    assert 7 in violations


def test_a_translation_of_feed_info_with_one_row_is_accepted():
    """`trnokey`: feed_info.txt has no key columns, so a translation of it carrying no
    record_id is accepted, and one carrying a record_id is an unexpected value.

    Named for the case it measured rather than the general claim it used to make. A parent with
    no key columns is *not* uniformly exempt: feed_info is `singleRow` and resolves to its first
    row, so a header-only feed_info violates, which
    test_a_single_row_table_resolves_to_its_first_row covers.
    """
    tables = dict(TABLES)
    tables["feed_info.txt"] = [{"_row_number": 2, "feed_publisher_name": "Pub"}]
    tables["translations.txt"] = [
        translation(2, "feed_info", field="feed_publisher_name"),
        translation(3, "feed_info", field="feed_publisher_name", language="de", record_id="X"),
    ]
    assert fire("translation_foreign_key_violation", tables) == []
    assert fire("translation_unexpected_value", tables) == [
        {"csvRowNumber": 3, "fieldName": "record_id", "fieldValue": "X"}
    ]


def test_one_row_missing_a_standard_field_silences_the_other_codes():
    """The first pass returning anything makes upstream return before the reference checks, so
    a feed can draw the missing-field notices and none of the other three codes."""
    tables = dict(TABLES)
    tables["translations.txt"] = [
        translation(2, "stops", record_id="NOPE"),
        translation(3, "stops", language=None, record_id="S1"),
        translation(4, "nosuchtable", record_id="X"),
    ]
    missing = [
        row
        for row in fire("missing_required_field", tables)
        if row["filename"] == "translations.txt"
    ]
    assert missing == [{"filename": "translations.txt", "csvRowNumber": 3, "fieldName": "language"}]
    assert fire("translation_foreign_key_violation", tables) == []
    assert fire("translation_unknown_table_name", tables) == []
    assert fire("translation_unexpected_value", tables) == []


@pytest.mark.parametrize(
    "code",
    [
        "translation_unknown_table_name",
        "translation_unexpected_value",
        "translation_foreign_key_violation",
    ],
)
def test_any_failed_table_silences_the_validator(code):
    """`trmixed`: the validator is injected with the feed container, so a stops.txt with a
    short row silences a translations row naming feed_info, a table that loaded perfectly.
    """
    tables = dict(TABLES)
    tables["translations.txt"] = [translation(2, "nosuchtable", record_id="X")]
    assert fire(code, tables, unindexable=frozenset({"stops.txt"})) == []


def test_the_validator_needs_the_table_name_column():
    """A translations.txt that does not declare table_name is skipped outright, before even the
    standard required fields are looked at."""
    tables = dict(TABLES)
    tables["translations.txt"] = [
        {"_row_number": 2, "field_name": "stop_name", "language": "fr", "translation": "Arret"}
    ]
    assert fire("translation_unknown_table_name", tables) == []
    assert [
        row
        for row in fire("missing_required_field", tables)
        if row["filename"] == "translations.txt"
    ] == []


# The six key-resolution shapes, measured on `trkeys`. Each one disagreed with plain string
# equality against the primary key, which is what the module used before the schema generator
# emitted the translation annotations.
KEY_CASES = [
    (
        "frequencies",
        "T1",
        "08:00:00",
        False,
        "a time key matches its spelling, not the stored seconds",
    ),
    ("stop_times", "T1", "+1", False, "parseInt accepts a leading plus"),
    ("calendar_dates", "SV", "00260101", True, "a date with leading zeros is a different date"),
    ("stop_areas", "A1", "S1", True, "both key columns are UNSUPPORTED, so the lookup is empty"),
    ("transfers", "S1", "S2", True, "the four unsupported key columns are not at their defaults"),
    (
        "stop_times",
        "T1",
        "notanint",
        True,
        "an unconvertible key throws upstream and matches nothing",
    ),
]


@pytest.mark.parametrize(("table", "record_id", "sub_id", "violates", "why"), KEY_CASES)
def test_the_lookup_reproduces_by_translation_key(table, record_id, sub_id, violates, why):
    tables = {
        "translations.txt": [translation(2, table, record_id=record_id, sub_id=sub_id)],
        "frequencies.txt": [
            {
                "_row_number": 2,
                "trip_id": "T1",
                "start_time": 28800,
                "end_time": 36000,
                "headway_secs": 600,
            }
        ],
        "stop_times.txt": STOP_TIMES,
        "calendar_dates.txt": [
            {"_row_number": 2, "service_id": "SV", "date": 20260101, "exception_type": 2}
        ],
        "stop_areas.txt": [{"_row_number": 2, "area_id": "A1", "stop_id": "S1"}],
        # from_trip_id is set, so the composite key's unsupported columns are not at default.
        "transfers.txt": [
            {
                "_row_number": 2,
                "from_stop_id": "S1",
                "to_stop_id": "S2",
                "from_trip_id": "T1",
                "transfer_type": 0,
            }
        ],
    }
    got = fire("translation_foreign_key_violation", tables)
    assert bool(got) is violates, f"{table}/{record_id}/{sub_id}: {why}"


def test_a_single_row_table_resolves_to_its_first_row():
    """`singleRow` tables ignore the ids entirely: any row satisfies the lookup and a
    header-only table satisfies nothing. feed_info.txt is the only such table at the pin."""
    base = {"translations.txt": [translation(2, "feed_info", field="feed_publisher_name")]}
    with_row = dict(base, **{"feed_info.txt": [{"_row_number": 2, "feed_publisher_name": "Pub"}]})
    assert fire("translation_foreign_key_violation", with_row) == []
    header_only = dict(base, **{"feed_info.txt": []})
    assert [row["tableName"] for row in fire("translation_foreign_key_violation", header_only)] == [
        "feed_info"
    ]


@pytest.mark.parametrize(
    ("table", "sub_id", "aborts"),
    [
        ("calendar_dates", "notadate", True),
        ("frequencies", "notatime", True),
        ("frequencies", "\u0660" + "08:00:00", True),
        ("stop_times", "notanint", False),
        ("stop_times", "\u0661", False),
        ("calendar_dates", "2026+101", False),
    ],
)
def test_only_an_integer_conversion_failure_is_caught(table, sub_id, aborts):
    """The generated method catches NumberFormatException and nothing else.

    So a bad integer key is an ordinary lookup miss, while a bad date or time propagates and
    aborts the validator: measured on the jar, which reports no translation notices and one
    runtime_exception_in_validator_error for each of the aborting cases. The two Unicode cases
    are the pair that shows why the typing stage's parsers cannot be reused here: Integer.parseInt
    accepts an Arabic-Indic digit, and GtfsTime's regex does not.
    """
    from gtfs_validator.rules._shared.translations import TranslationConversionError

    tables = {
        "translations.txt": [
            translation(
                2, table, record_id="T1" if table != "calendar_dates" else "SV", sub_id=sub_id
            )
        ],
        "stop_times.txt": STOP_TIMES,
        "frequencies.txt": [
            {
                "_row_number": 2,
                "trip_id": "T1",
                "start_time": 28800,
                "end_time": 36000,
                "headway_secs": 600,
            }
        ],
        "calendar_dates.txt": [
            {"_row_number": 2, "service_id": "SV", "date": 20260101, "exception_type": 2}
        ],
    }
    if aborts:
        with pytest.raises(TranslationConversionError):
            fire("translation_foreign_key_violation", tables)
    else:
        fire("translation_foreign_key_violation", tables)


def test_one_id_in_two_files_is_reported_with_both_positions():
    """Measured on `misc3`: the context omits the field for a file that does not carry the id, so a
    notice carries two of the three. A stop sharing an id with a GeoJSON feature reports
    csvRowNumberA and featureIndex; one sharing with a location group reports A and B.
    """
    tables = {
        "stops.txt": [
            {"_row_number": 4, "stop_id": "SHARED_GRP"},
            {"_row_number": 5, "stop_id": "SHARED_GEO"},
            {"_row_number": 6, "stop_id": "S1"},
        ],
        "location_groups.txt": [{"_row_number": 2, "location_group_id": "SHARED_GRP"}],
        "locations.geojson": [
            {
                "_row_number": 0,
                "feature_id": "SHARED_GEO",
                "feature_index": 0,
                "geometry_type": "Polygon",
            }
        ],
    }
    assert sorted_rows(fire("duplicate_geography_id", tables)) == sorted_rows(
        [
            {"geographyId": "SHARED_GEO", "csvRowNumberA": 5, "featureIndex": 0},
            {"geographyId": "SHARED_GRP", "csvRowNumberA": 4, "csvRowNumberB": 2},
        ]
    )


def test_an_id_repeated_within_one_file_is_not_this_notice():
    """The test is on the number of distinct *files*, so a duplicate inside one file is
    duplicate_key's business and this rule stays quiet."""
    tables = {
        "stops.txt": [
            {"_row_number": 2, "stop_id": "TWICE"},
            {"_row_number": 3, "stop_id": "TWICE"},
        ],
    }
    assert fire("duplicate_geography_id", tables) == []
