"""The libphonenumber tables and regexes parse() consults, as dumped from the jar.

Everything here is data plus the two accessors that shape it: the algorithm that
uses it lives in phones.py. The split exists because the constants are a
transcription of libphonenumber's own, and reading them next to the parse steps
they feed makes both harder to check.

Regenerated by tools/sync_reference_data.py; never hand-edited.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from importlib.resources import files

MIN_LENGTH_FOR_NSN = 2
MAX_LENGTH_FOR_NSN = 17
MAX_INPUT_STRING_LENGTH = 250
MAX_LENGTH_COUNTRY_CODE = 3

UNKNOWN_COUNTRY = "ZZ"
NON_GEOGRAPHICAL_REGION = "001"
# libphonenumber's PLUS_CHARS. The second is FULLWIDTH PLUS SIGN, spelled as an
# escape so it cannot be mistaken for an ASCII "+" when read.
PLUS_CHARS = "+\uff0b"

# Where a country calling code came from, which decides whether the default
# region's rules apply at all.
FROM_DEFAULT_COUNTRY = "default"
FROM_NUMBER_WITH_PLUS_SIGN = "plus"
FROM_NUMBER_WITH_IDD = "idd"

# Outcomes of testNumberLength. isPossibleNumber accepts the first two.
IS_POSSIBLE = "possible"
IS_POSSIBLE_LOCAL_ONLY = "local_only"
TOO_SHORT = "too_short"
TOO_LONG = "too_long"
INVALID_LENGTH = "invalid_length"


@lru_cache(maxsize=1)
def tables() -> dict:
    return json.loads(files("gtfs_validator.data").joinpath("phone_lengths.json").read_text())


def java_regex(pattern: str) -> str:
    """Translate the Java spellings libphonenumber's patterns use.

    ``\\p{Nd}`` is Python's ``\\d`` on a str pattern (both are the Unicode
    decimal-digit category), and the possessive quantifiers have no Python
    equivalent. Dropping possessiveness is safe here: it only forbids
    backtracking, so it can never widen what a pattern accepts.
    """
    return pattern.replace(r"\p{Nd}", r"\d").replace("*+", "*").replace("++", "+")


# java.util.regex.Pattern flag bits, so a dumped pattern is compiled the way Java
# compiled it. UNICODE_CASE is the default for a Python str pattern and DOTALL is
# spelled the same, so only these three need translating.
JAVA_CASE_INSENSITIVE = 0x02
JAVA_MULTILINE = 0x08
JAVA_DOTALL = 0x20


@lru_cache(maxsize=8)
def pattern(name: str) -> re.Pattern[str]:
    """Compile a dumped pattern with the flags Java compiled it with.

    The flags are not uniform across libphonenumber's patterns: only EXTN_PATTERN
    and VALID_PHONE_NUMBER_PATTERN are case insensitive. Compiling the whole set
    that way makes SECOND_NUMBER_START_PATTERN's "/x" match "/X", which
    libphonenumber does not treat as the start of a second number.
    """
    raw = tables()["patterns"][name]
    flags = 0
    if raw["flags"] & JAVA_CASE_INSENSITIVE:
        flags |= re.IGNORECASE
    if raw["flags"] & JAVA_MULTILINE:
        flags |= re.MULTILINE
    if raw["flags"] & JAVA_DOTALL:
        flags |= re.DOTALL
    return re.compile(java_regex(raw["pattern"]), flags)


def constant(name: str) -> str:
    """An RFC 3966 marker string, as dumped from libphonenumber."""
    return tables()["constants"][name]


@lru_cache(maxsize=1)
def iso_countries() -> frozenset[str]:
    """Locale.getISOCountries(), the set upstream's CountryCode accepts.

    Wider than libphonenumber's supported regions: "AQ" is a country with no
    phone metadata, and upstream still validates against it rather than skipping.
    """
    return frozenset(tables()["iso_countries"])


@lru_cache(maxsize=1)
def alpha_mappings() -> dict[str, str]:
    """ALPHA_PHONE_MAPPINGS, dumped from the jar rather than reconstructed.

    Its name misleads: it holds the 26 keypad letters plus the *ASCII* digits and
    nothing else, 36 entries in all. normalize() uses it for a vanity number, so
    on that path a fullwidth or Arabic-Indic digit is dropped rather than folded,
    even though the digits-only path keeps it. Building the map from
    libphonenumber's wider digit set gets that exactly backwards.
    """
    return {chr(int(code, 16)): digit for code, digit in tables()["alpha_mappings"].items()}
